# Generated by Django 2.2 on 2019-05-02 22:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=500)),
                ('suporte', models.CharField(max_length=500)),
                ('comando', models.CharField(max_length=500)),
                ('dificuldade', models.CharField(choices=[('muito_facil', 'Muito Fácil'), ('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil'), ('muito_dificil', 'Muito Difícil')], max_length=30)),
                ('curso', models.CharField(max_length=30)),
                ('unidade_curricular', models.CharField(max_length=45)),
                ('autor', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
