# Generated by Django 2.2 on 2019-05-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('imagem', models.ImageField(upload_to='itens/media')),
                ('correta', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='alternativas',
            field=models.ManyToManyField(to='itens.Alternativa'),
        ),
    ]
