# Generated by Django 2.2 on 2019-06-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='texto',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='comando',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='enunciado',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='suporte',
            field=models.TextField(max_length=500),
        ),
    ]
