# Generated by Django 2.2 on 2019-05-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0002_auto_20190502_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='imagem',
            field=models.ImageField(upload_to='media'),
        ),
    ]
