# Generated by Django 2.2 on 2019-05-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0003_auto_20190502_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='imagem',
            field=models.ImageField(upload_to='imagem_alternativas'),
        ),
    ]
