# Generated by Django 2.2 on 2019-06-23 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0005_auto_20190618_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='curso',
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='itens.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=254)),
                ('materias', models.ManyToManyField(to='itens.Materias')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='cursos',
            field=models.ManyToManyField(to='itens.Cursos'),
        ),
    ]
