# Generated by Django 2.2 on 2019-06-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0005_auto_20190625_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='unidades_curriculares',
        ),
        migrations.AddField(
            model_name='item',
            name='unidades_curriculares',
            field=models.ManyToManyField(to='itens.UnidadeCurricular'),
        ),
    ]
