# Generated by Django 2.2 on 2019-06-23 01:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itens', '0006_auto_20190623_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='docente',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
